env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/kvstore-server/main.go
    id: "kvstore-server"
    binary: kvstore-server
    ldflags:
      - -X main.Version={{.Version}} -X main.Build={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
    goarch:
      - 386
      - arm
      - arm64
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: 386
      - goos: openbsd
        goarch: 386
      - goos: netbsd
        goarch: 386
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: netbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: netbsd
        goarch: amd64

  - main: ./cmd/kvstore-cli/main.go
    id: "kvstore-cli"
    binary: kvstore-cli
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
    goarch:
      - 386
      - arm
      - arm64
      - amd64
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
