name: Publish kvstore server image
on:
  workflow_run:
    workflows: ["Ci"]
    types:
      - completed

jobs:
  push_to_registry:
    name: Push kvstore server Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set version
        id: meta
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          push: true
          repository: hotpotatoc123/kvstore-server
          file: "./build/kvstore-server/Dockerfile"
          tags: ${{ steps.meta.outputs.tag }}
